name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.10
  - notebook=6.2.0
  - ipython=7.21.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - jinja2=2.11.3
  - protobuf
  - pip:
      - wandb==0.10.31